# This inc file contains the versions and SRCREV for individual
# RDK hal header recipes present in rdk-e/meta-rdk-halif-headers

CMF_GITHUB_ROOT ?= "git://github.com/rdkcentral"
CMF_GITHUB_PROTOCOL ?= "git"
CMF_GITHUB_SRC_URI_SUFFIX ?= "protocol=${CMF_GITHUB_PROTOCOL};nobranch=1"

PV_pn-media-utils-headers = "1.0.4"
PR_pn-media-utils-headers = "r0"
SRCREV_pn-media-utils-headers = "1.0.4"

PV_pn-hdmicecheader = "1.3.7"
PR_pn-hdmicecheader = "r0"
SRCREV_pn-hdmicecheader = "1.3.7"

PV_pn-deepsleep-manager-headers = "1.0.3"
PR_pn-deepsleep-manager-headers = "r0"
SRCREV_pn-deepsleep-manager-headers = "1.0.3"

PV_pn-power-manager-headers = "1.0.2"
PR_pn-power-manager-headers = "r0"
SRCREV_pn-power-manager-headers = "1.0.2"

PV_pn-devicesettings-hal-headers = "2.0.0"
PR_pn-devicesettings-hal-headers = "r0"
SRCREV_pn-devicesettings-hal-headers = "2.0.0"

PV_pn-tvsettings-hal-headers = "1.2.0"
PR_pn-tvsettings-hal-headers = "r0"
SRCREV_pn-tvsettings-hal-headers = "1.2.0"

PV_pn-iarmmgrs-hal-headers = "2.0.1"
PR_pn-iarmmgrs-hal-headers = "r0"
SRCREV_pn-iarmmgrs-hal-headers = "bfc2109722905b76d7234a6a49b7706028741547"

PV_pn-closedcaption-hal-headers = "1.0.0"
PR_pn-closedcaption-hal-headers = "r0"
SRCREV_pn-closedcaption-hal-headers = "GRT_v2"

PV_pn-iarmbus-headers = "1.0.0"
PR_pn-iarmbus-headers = "r0"
SRCREV_pn-iarmbus-headers = "GRT_v2"

PV_pn-rdk-gstreamer-utils-headers = "1.3.0"
PR_pn-rdk-gstreamer-utils-headers = "r0"
SRCREV_pn-rdk-gstreamer-utils-headers = "1.3.0"
